Repository NexGenAnalytics/Trilinos, pull requests merged in 2023-08, with the labels that each got.

#100 #90: Remove use of `MPI_COMM_WORLD` from Belos package
  packages/belos/epetra/src/BelosEpetraUtils.cpp
  packages/belos/src/BelosGlobalComm.hpp
  packages/belos/src/BelosOutputManager.hpp
  packages/belos/src/CMakeLists.txt
Labels: EpetraMPI T1

#88 #87: Framework: Add CI
  .github/workflows/ci-mpi-epetraoff.yml
  nga-ci/build.sh
  nga-ci/nga-ci.dockerfile
  nga-ci/test.sh
Labels: EpetraMPI T2

#113 #98: Pike: Remove use of MPI_COMM_WORLD
  packages/pike/blackbox/src/Pike_GlobalComm.hpp
  packages/pike/blackbox/src/Pike_MultiphysicsDistributor.cpp
Labels: EpetraMPI T1

#109 #95: Remove use of MPI_COMM_WORLD from NOX package
  packages/nox/src/CMakeLists.txt
  packages/nox/src/NOX_Description.H
  packages/nox/src/NOX_GlobalComm.H
  packages/nox/src/NOX_Utils.C
Labels: EpetraMPI T1

#147 #144: EpetraExt: Use EpetraExt namespace when calling `get_global_comm`
  packages/epetraext/src/inout/EpetraExt_GlobalComm.h
  packages/epetraext/src/inout/EpetraExt_HDF5.cpp
Labels: NGA-internal, EpetraMPI T1

#146 #145: Belos: Explicitly use Belos namespace when calling `get_global_comm`
  packages/belos/epetra/src/BelosEpetraUtils.cpp
  packages/belos/src/BelosGlobalComm.hpp
  packages/belos/src/BelosOutputManager.hpp
Labels: NGA-internal, EpetraMPI T1
